# Generated by Django 2.1.5 on 2019-10-15 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0007_auto_20191014_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
