# Generated by Django 2.1.4 on 2019-09-20 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
        ('users', '0005_auto_20190918_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quetion_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compiler.Question'),
            preserve_default=False,
        ),
    ]
