# Generated by Django 2.1.4 on 2019-09-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_quetion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quetion_id',
        ),
    ]
