# Generated by Django 2.1.5 on 2019-10-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20191013_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask_question',
            old_name='user',
            new_name='author',
        ),
    ]
