# Generated by Django 2.1.5 on 2019-10-15 14:35

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_auto_20191013_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask_question',
            name='code',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='code',
        ),
        migrations.AddField(
            model_name='ask_question',
            name='description',
            field=ckeditor.fields.RichTextField(default='oct 15 2019 20:04:39'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ask_question',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ask_question',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solution',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solution',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
