# Generated by Django 2.1.5 on 2019-10-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_auto_20191015_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask_question',
            name='question',
            field=models.CharField(max_length=3000),
        ),
    ]
