# Generated by Django 2.1.5 on 2019-12-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_auto_20191015_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.FileField(default='', upload_to='Question'),
            preserve_default=False,
        ),
    ]
