# Generated by Django 2.1.5 on 2019-12-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0010_auto_20191206_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Question'),
        ),
    ]
