# Generated by Django 2.1.5 on 2019-12-06 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queries', '0011_auto_20191206_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution_Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.Solution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='solution_like',
            unique_together={('user', 'solution')},
        ),
    ]
