# Generated by Django 2.1.4 on 2019-09-20 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCompiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3000)),
                ('user_input', models.CharField(max_length=300)),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(choices=[('python', 'python'), ('c', 'c'), ('cpp', 'cpp'), ('java', 'java'), ('js', 'js')], default='c', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_author', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('que', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('constraint', models.TextField()),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testinput', models.CharField(max_length=100)),
                ('testoutput', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.Question')),
            ],
        ),
    ]
