# Generated by Django 2.1.4 on 2019-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompiler',
            name='user_input',
            field=models.CharField(default='', max_length=300),
        ),
    ]
