# Generated by Django 2.1.4 on 2019-09-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_auto_20190922_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompiler',
            name='user_input',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
