# Generated by Django 2.1.5 on 2019-10-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_auto_20190925_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompiler',
            name='language',
            field=models.CharField(choices=[('python', 'python'), ('python3', 'python3'), ('c', 'c'), ('cpp', 'cpp'), ('java', 'java'), ('js', 'js')], default='c', max_length=6),
        ),
    ]
