# Generated by Django 2.1.4 on 2019-09-29 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20190929_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='date_upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
