# Generated by Django 2.1.5 on 2019-10-16 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0003_tutorial_date_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateliked', models.DateTimeField(default=django.utils.timezone.now)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Tutorial')),
                ('userlike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
